name:                day21
version:             0.1.0.0
github:              "vescoc/day21"
license:             BSD3
author:              "vescoc"
maintainer:          "claudio.vesco@gmail.com"
copyright:           "2021 vescoc"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/vescoc/day21#readme>

dependencies:
- base >= 4.7 && < 5
- time

library:
  source-dirs: src

executables:
  day21-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - day21

tests:
  day21-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - day21
    - hspec
